# 是否输出域名记录查询返回信息。(用于调试)
debug: true

service:
  # 更新间隔,单位为秒。
  period: 900
  # 阿里云接口地域ID，可以不改动。
  # 请参考 https://help.aliyun.com/knowledge_detail/40654.html
  region-id: cn-hangzhou
 
# 本机IP查询接口配置。
# 用于获取对应的IP地址，以更新到域名记录。
query:
  # IPv4地址获取链接
  v4: http://ifconfig.me/ip
  # IPv6地址获取链接 (可选)
  # 如不需要IPV6，则可以直接将地址留空。
  v6: https://v6.ip.zxinc.org/getip
 
# 更新任务配置。
# 具体配置请参考 https://github.com/CarmJos/AliDDNS-Updater/blob/master/.doc/REQUEST.md
requests:
  demo:
    domain: example.com
    record: '@'
    ipv6: false
    access-key: YOUR-ACCESS-KEY
    access-secret: YOUR-ACCESS-SECRET
# 配置文件版本，请不要修改。
version: 2.0

# 是否检查本程序更新。(默认开启)
check-update: true

