# 是否输出域名记录查询返回信息。(用于调试)
debug: true

# 更新间隔,单位为秒。
period: 900
# 阿里云接口地域ID，可以不改动。
region: cn-hangzhou

ipv4Hosts: [http://members.3322.org/dyndns/getip]
ipv6Hosts: [https://v6.ip.zxinc.org/getip]

# 更新任务配置。
# 具体配置请参考 https://github.com/CarmJos/AliDDNS-Updater/blob/master/.doc/REQUEST.md
aliyunConfigMap:
  nextcloud:
    domain: opengpt.pub
    record: nextcloud
    protocol: ipv4
    accessKey: 111
    accessSecret: 222
